#!/usr/bin/env zsh

export PATH="$PATH:/usr/local/bin:/usr/bin:/bin"
ARCHIVIST_CONFIG=${ARCHIVIST_CONFIG:-$HOME/.config/archivist/config}
[ -f $ARCHIVIST_CONFIG ] && source $ARCHIVIST_CONFIG
ARCHIVIST_DATA_DIR=${ARCHIVIST_DATA_DIR:-$HOME/.local/share/archivist}
mkdir -p $ARCHIVIST_DATA_DIR
ARCHIVIST_IGNORE_URL_FILE=${ARCHIVIST_IGNORE_URL_FILE:-$HOME/.config/archivist/ignore.conf}
touch $ARCHIVIST_IGNORE_URL_FILE # the file must include web.archive.org
[[ -z $RAINDROP_TEST_TOKEN ]] && echo "Set \$RAINDROP_TEST_TOKEN variable before execution" && exit 1

auth="Authorization: Bearer $RAINDROP_TEST_TOKEN"
root='https://api.raindrop.io/rest/v1'

curl -s "$root/raindrops/-1?page=0&perpage=30" -H $auth |
jq -r '.items[].link' |
grep -vFf $ARCHIVIST_IGNORE_URL_FILE |
/usr/local/bin/httpx -nc -silent -sc |
awk -F '[] []' '{print $3","$1}'
