#!/usr/bin/env zsh

ARCHIVIST_CONFIG=${ARCHIVIST_CONFIG:-$HOME/.config/archivist/config}
source $ARCHIVIST_CONFIG
ARCHIVIST_DATA_DIR=${ARCHIVIST_DATA_DIR:-$HOME/.local/share/archivist}
ARCHIVIST_IGNORE_URL_FILE=${ARCHIVIST_IGNORE_URL_FILE:-$HOME/.config/archivist/ignore.conf}
